package com.gestionssii.model;
// Generated 27 avr. 2017 17:45:17 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;



/**
 * Exams generated by hbm2java
 */
@Entity
@Table(name = "exams", catalog = "gestion_ssii")
@Proxy(lazy = false)
public class Exams implements java.io.Serializable {

	private Integer idExams;
	private String name;
	private String expertise;
	private Integer level;
	private Integer time;
	private Integer active;
	
	private Set<Question> questions = new HashSet<Question>(0);

	public Exams() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idExams", unique = true, nullable = false)
	public Integer getIdExams() {
		return this.idExams;
	}

	public void setIdExams(Integer idExams) {
		this.idExams = idExams;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "expertise", length = 80)
	public String getExpertise() {
		return this.expertise;
	}

	public void setExpertise(String expertise) {
		this.expertise = expertise;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "time")
	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "exams")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
