package com.gestionssii.model;
// Generated 27 avr. 2017 17:45:17 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inviteexams generated by hbm2java
 */
@Entity
@Table(name = "inviteexams", catalog = "gestion_ssii")
public class Inviteexams implements java.io.Serializable {

	private Integer idInviteExams;
	private int idExams;
	private int ispassed;
	private String description;

	public Inviteexams() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idInviteExams", unique = true, nullable = false)
	public Integer getIdInviteExams() {
		return this.idInviteExams;
	}

	public void setIdInviteExams(Integer idInviteExams) {
		this.idInviteExams = idInviteExams;
	}

	@Column(name = "idExams", nullable = false)
	public int getIdExams() {
		return this.idExams;
	}

	public void setIdExams(int idExams) {
		this.idExams = idExams;
	}

	@Column(name = "ispassed", nullable = false)
	public int getIspassed() {
		return this.ispassed;
	}

	public void setIspassed(int ispassed) {
		this.ispassed = ispassed;
	}

	@Column(name = "description", nullable = false, length = 90)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
