package com.gestionssii.model;
// Generated 27 avr. 2017 17:45:17 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "gestion_ssii")
@Proxy(lazy = false)
public class Question implements java.io.Serializable {

	private Integer idQuestion;
	private Categorie categorie;
	private Exams exams;
	private String description;

	private Set<Reponse> reponses = new HashSet<Reponse>(0);

	public Question() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idQuestion", unique = true, nullable = false)
	public Integer getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(Integer idQuestion) {
		this.idQuestion = idQuestion;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.REMOVE)
	@JoinColumn(name = "idCategorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.REMOVE)
	@JoinColumn(name = "idExams", nullable = false)
	public Exams getExams() {
		return this.exams;
	}

	public void setExams(Exams exams) {
		this.exams = exams;
	}

	@Column(name = "description", length = 120)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "question",cascade = CascadeType.REMOVE)
	public Set<Reponse> getReponses() {
		return this.reponses;
	}

	public void setReponses(Set<Reponse> reponses) {
		this.reponses = reponses;
	}

}
