package com.gestionssii.model;
// Generated 27 avr. 2017 17:45:17 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reponse generated by hbm2java
 */
@Entity
@Table(name = "reponse", catalog = "gestion_ssii")
public class Reponse implements java.io.Serializable {

	private Integer idReponse;
	private Question question;
	private String description;
	private Integer isGoodreponse;

	public Reponse() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idReponse", unique = true, nullable = false)
	public Integer getIdReponse() {
		return this.idReponse;
	}

	public void setIdReponse(Integer idReponse) {
		this.idReponse = idReponse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idQuestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "description", length = 80)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isGoodreponse")
	public Integer getIsGoodreponse() {
		return this.isGoodreponse;
	}

	public void setIsGoodreponse(Integer isGoodreponse) {
		this.isGoodreponse = isGoodreponse;
	}

}
